In [1]:
import pandas as pd

In [2]:
ds=pd.read_csv('SalaryData.csv')

In [3]:
x=ds['YearsExperience']

In [4]:
x=x.values.reshape(30,1)

In [5]:
y=ds['Salary']
y=y.values.reshape(30,1)

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
mind=LinearRegression()

In [8]:
mind.fit(x,y)

LinearRegression()

In [9]:
mind.coef_

array([[9449.96232146]])

In [10]:
mind.intercept_

array([25792.20019867])

In [11]:
mind.predict([[2.2]])

array([[46582.11730587]])

In [12]:
import joblib

In [13]:
joblib.dump(mind,'salary_pred.pk1')

['salary_pred.pk1']