In [2]:
import pandas as pd

In [3]:
ds=pd.read_csv('SalaryData.csv')

In [14]:
x=ds['YearsExperience']

In [18]:
x=x.values.reshape(30,1)

In [22]:
y=ds['Salary']
y=y.values.reshape(30,1)

In [23]:
from sklearn.linear_model import LinearRegression

In [25]:
mind=LinearRegression()

In [26]:
mind.fit(x,y)

LinearRegression()

In [33]:
mind.coef_

array([[9449.96232146]])

In [34]:
mind.intercept_

array([25792.20019867])

In [35]:
mind.predict([[2.2]])

array([[46582.11730587]])

In [30]:
import joblib

In [36]:
joblip.dump(mind,'salary_pred.pk1')

NameError: name 'joblip' is not defined